name: Lint Code Base

# on: [push, pull_request]
on:
  push:
    branches: [ "master" ]
  pull_request_target:
    types: [opened]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          LINTER_RULES_PATH: .github/linters/
          JAVA_FILE_NAME: checkstyle.xml
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
